### ISSUE TITLE
Error on laravel 3.2.1

### ISSUE THREAD

**Issue by JoshZA** [ShawnMcCool/laravel-form-base-model#2]
Not sure if this is example code or what the issue is here, but this is what I get when accessing page 2 of your multipage example.

```
Array to string conversion

Location:

E:\backup\xampp\htdocs\laravel\laravel\input.php on line 43

Stack Trace:

#0 E:\backup\xampp\htdocs\laravel\laravel\laravel.php(40): Laravel\Error::native(8, 'Array to string conversion', 'E:\backup\xampp\htdocs\laravel\laravel\input.php', 43)
#1 E:\backup\xampp\htdocs\laravel\laravel\input.php(43): Laravel\{closure}(8, 'Array to string conversion', 'E:\backup\xampp\htdocs\laravel\laravel\input.php', 43, Array)
#2 E:\backup\xampp\htdocs\laravel\bundles\form-base-model\formbase_model.php(186): Laravel\Input::has('favorite_foods')
#3 E:\backup\xampp\htdocs\laravel\bundles\form-base-model\controllers\examples.php(108): FormBase_Model::save_input(Array)
#4 [internal function]: Form_Base_Model_Examples_Controller->post_multi_page_example_two()
#5 E:\backup\xampp\htdocs\laravel\laravel\routing\controller.php(323): call_user_func_array(Array, Array)
#6 E:\backup\xampp\htdocs\laravel\laravel\routing\controller.php(283): Laravel\Routing\Controller->response('multi_page_example_two', Array)
#7 E:\backup\xampp\htdocs\laravel\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('multi_page_example_two', Array)
#8 E:\backup\xampp\htdocs\laravel\laravel\routing\route.php(153): Laravel\Routing\Controller::call('form-base-model::examples@(:1)', Array)
#9 E:\backup\xampp\htdocs\laravel\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#10 E:\backup\xampp\htdocs\laravel\laravel\laravel.php(125): Laravel\Routing\Route->call()
#11 E:\backup\xampp\htdocs\laravel\public\index.php(34): require('E:\backup\xampp\htdocs\laravel\laravel\laravel.php')
```

**Comment by ShawnMcCool** [comment]
I wonder if anyone else has this issue.

**Comment by JoshZA** [comment]
Just upgraded bundle, and my dev environment has changed. XAMPP Windows (1.8.0-beta8):
    Apache (2.4.2)
    MySQL (5.5.25)
    PHP (5.4.4)

Works when I don't set Favorite Foods, fails otherwise

**Comment by ShawnMcCool** [comment]
I'll need to test with the newest xampp beta. I probably can't do it today. But, soon.

**Comment by ShawnMcCool** [comment]
I'm having no issues in any testing situation. For now I'm going to close this issue.

**Comment by plogik** [comment]
Got this error too after upgrade to php 5.4, seems php versions over 5.3 are more restrictive with type hinting. Or maybe this is due to more restrictive settings in MAMP 2.2 (was using MAMP 2.0). 

Problem is that "has" in laravel/input:23 assumes that the value is a key. My value was an array. Quick fix:

```
public static function has($key)
{
    $val = static::get($key);
    return $val && ((is_string($val) && strlen(trim($val))) || is_array($val));
    //return trim((string) static::get($key)) !== '';
}
```
