### ISSUE TITLE
Foods is Undefined.

### ISSUE THREAD

**Issue by AlexisSerneels** [ShawnMcCool/laravel-form-base-model#3]
On the review page of the multi_page example, here is the error :

```
Unhandled Exception
Message:

Undefined variable: foods

Location:

/Applications/MAMP/htdocs/laravel/laravel/view.php(354) : eval()'d code on line 30

Stack Trace:

#0 /Applications/MAMP/htdocs/laravel/laravel/laravel.php(40): Laravel\Error::native(8, 'Undefined varia...', '/Applications/M...', 30)
#1 /Applications/MAMP/htdocs/laravel/laravel/view.php(354) : eval()'d code(30): Laravel\{closure}(8, 'Undefined varia...', '/Applications/M...', 30, Array)
#2 /Applications/MAMP/htdocs/laravel/laravel/view.php(354): eval()
#3 /Applications/MAMP/htdocs/laravel/laravel/blade.php(71): Laravel\View->get()
#4 [internal function]: Laravel\{closure}(Object(Laravel\View))
#5 /Applications/MAMP/htdocs/laravel/laravel/event.php(199): call_user_func_array(Object(Closure), Array)
#6 /Applications/MAMP/htdocs/laravel/laravel/event.php(138): Laravel\Event::fire('laravel.view.en...', Array, true)
#7 /Applications/MAMP/htdocs/laravel/laravel/view.php(325): Laravel\Event::until('laravel.view.en...', Array)
#8 /Applications/MAMP/htdocs/laravel/laravel/view.php(546): Laravel\View->render()
#9 /Applications/MAMP/htdocs/laravel/laravel/response.php(246): Laravel\View->__toString()
#10 /Applications/MAMP/htdocs/laravel/laravel/laravel.php(138): Laravel\Response->render()
#11 /Applications/MAMP/htdocs/laravel/public/index.php(34): require('/Applications/M...')
#12 {main}
```

**Comment by ShawnMcCool** [comment]
Thanks, I'll look into this asap.

**Comment by ShawnMcCool** [comment]
It appears that your review view is missing the following line:

```
<? $foods = ExampleForm::old( 'favorite_foods', array() ); // workaround for blade forelse bug that i only just now found ?>
```

This should be on line 28. Alternately, try to change <? to <?php if your server doesn't have short tags enabled. I'll change this in a future version just in case people don't enable short tags.

**Comment by AlexisSerneels** [comment]
`<?`
Correct ! Thx. Shawn.
